import "./clown.spec.mjs"
import "./0_1_execWith.spec.mjs"
import "./0_2_Pipe.spec.mjs"
import "./1_GetLatestVersion.spec.mjs"
import "./2_MakeNewVersion.spec.mjs"
import "./3_ExitIfNoVersion.spec.mjs"
// import "./4_GetVersionCommit.spec.mjs"
// import "./5_GetChanges.spec.mjs"
// import "./6_ForceBump.spec.mjs"
// import "./7_MakeChangelog.spec.mjs"
// import "./8_Log.spec.mjs"
